name = "SFS"
defaultTargets = ["SFS", "DSL", "Root", "Core"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "SFS"

[[lean_lib]]
name = "DSL"

[[lean_lib]]
name = "Root"

[[lean_lib]]
name = "Core"
