/-
Lean 4 formalization of the KerML (Kernel Modeling Language, OMG SysML v2 Release,
"Kernel Modeling Language v1.0 Beta 3") **Root** package's metamodel: KerML §8.2.3
"Root Concrete Syntax" and §8.3.2 "Root Abstract Syntax".

This is a *different* formalization concern from `SFS.lean`: `SFS.lean` translates
`~/git3/set.mm/SFS.mm`'s Metamath-level Supplemental Formal Semantics content (BLESS
Logic, Mereology, `df-model`, `df-rep`/`ElementRep`, `df-kind`/`ElementKind`, ...),
where `KElement` is a deliberately opaque stand-in ("SFS.mm has no Element/design
primitive to reuse"). *This* file instead formalizes the real KerML metamodel itself
-- the actual `Element`/`Relationship`/`Namespace`/... metaclasses the OMG spec
defines -- as its own independent structure, not identified with `SFS.lean`'s
`KElement`/`ElementRep`/`ElementKind` (those remain unchanged).

## Scope (structural only, matching this project's established `KElement`/`Design`
precedent in `SFS.lean` for "whole containment graph" complexity)

Each metaclass below is a Lean `structure`, using `extends` to mirror KerML's
generalization hierarchy directly (Lean 4 structure extension gives real
subtyping-like projections, unlike a flat translation). Only **non-derived** (stored)
attributes are given fields; attributes marked `/` in the spec (derived, computed by
an OCL formula from other model state -- `owner`, `qualifiedName`, `ownedElement`,
`member`, effectively all of `Namespace`'s own attributes, etc.) are *not* included as
fields. Most of what's dropped this way is exactly the containment-graph structure
(`Element.ownedRelationship`, `Relationship.ownedRelatedElement`/`owningRelatedElement`
/`relatedElement`, `Namespace.member`/`ownedMember`/...): faithfully modeling that
graph would need `Element` and `Relationship` to reference each other, and doing that
justice (well-formedness of the ownership tree, name resolution, `qualifiedName`
computation, ...) is a substantially bigger project, deliberately out of scope here,
the same judgment call this project already made for `SFS.lean`'s opaque `KElement`
and `Design`. What *is* kept: every metaclass's own non-derived, non-graph-structural
attributes (`elementId`, `declaredName`, `client`/`supplier`, `memberName`,
`visibility`, ...) and the generalization hierarchy itself.

OCL **constraints** (derivation/semantic/validation) are noted in prose in each
metaclass's doc comment, not encoded as Lean propositions or proved -- consistent with
the same "structural, not deeply verified" scope already used for `ElementRep`/
`ElementKind`/`Model` in `SFS.lean`.

No file in this project currently depends on `Root.lean`; it's a freestanding
formalization, imported by `Core.lean` (KerML §8.2.4/§8.3.3).
-/

namespace KerML.Root

/-- KerML §8.3.2.1.2 `Element`. "A constituent of a model that is uniquely identified
relative to all other Elements. It can have Relationships with other Elements. Some of
these Relationships might imply ownership of other Elements, which means that if an
Element is deleted from a model, then so are all the Elements that it owns."
Non-derived attributes only (see file header) -- `ownedRelationship`, `/owner`,
`/qualifiedName`, `/name`, `/ownedElement`, `/documentation`, etc. are all omitted. -/
structure Element where
  /-- The globally unique identifier for this Element (set by tooling, must not
  change during the Element's lifetime). -/
  elementId : String
  /-- Alternative identifiers for this Element, generally set by tools. -/
  aliasIds : List String := []
  /-- The declared name of this Element. -/
  declaredName : Option String := none
  /-- An optional shorter/more succinct alternative name. -/
  declaredShortName : Option String := none
  deriving Repr

/-- KerML §8.3.2.1.3 `Relationship`. "An Element that relates other Element[s]. Some
of its relatedElements may be owned, in which case those ownedRelatedElements will be
deleted from a model if their owningRelationship is. ... The relatedElements of a
Relationship are divided into source and target Elements." Per the file header,
`ownedRelatedElement`/`owningRelatedElement`/`source`/`target`/`/relatedElement`
(the containment-graph edges) are deliberately omitted -- only `isImplied` is kept. -/
structure Relationship extends Element where
  /-- Whether this Relationship was generated by tooling to meet semantic rules,
  rather than being directly created by a modeler. -/
  isImplied : Bool := false
  deriving Repr

/-- KerML §8.3.2.2.2 `Dependency`. "A Relationship that indicates that one or more
client Elements require one more supplier Elements for their complete specification.
... entirely a model-level Relationship, without instance-level semantics." `client`
redefines `source`, `supplier` redefines `target` (both spec multiplicity `[1..*]`,
not enforced here). -/
structure Dependency extends Relationship where
  client : List Element
  supplier : List Element
  deriving Repr

/-- KerML §8.3.2.3.2 `AnnotatingElement`. "An Element that provides additional
description of or metadata on some other Element. ... either attached to its
annotatedElements by Annotation Relationships, or it implicitly annotates its
owningNamespace." Abstract in the spec (only `Comment`/`Documentation`/
`TextualRepresentation`/`MetadataFeature` are concretely instantiated); Lean doesn't
enforce that. All its own attributes (`annotatedElement`, `annotation`, ...) are
derived, so no extra fields beyond `Element`'s. -/
structure AnnotatingElement extends Element where
  deriving Repr

/-- KerML §8.3.2.3 `Annotation` (the Relationship an `AnnotatingElement` uses to
attach to what it annotates). `annotatedElement` redefines `target`. Spec constraint:
exactly one of `ownedAnnotatingElement`/`owningAnnotatingElement` is non-null (both
derived, not encoded here). -/
structure Annotation extends Relationship where
  annotatedElement : Element
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.2 `Comment`. An `AnnotatingElement` whose `body` is
free-text (possibly marked-up, e.g. HTML) annotation content. -/
structure Comment extends AnnotatingElement where
  body : String
  /-- POSIX locale of `body`'s natural-language text, if specified. -/
  locale : Option String := none
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.2 `Documentation`, a `Comment` whose `documentedElement`
(derived = its `owner`) is what it documents -- no extra stored attributes. -/
structure Documentation extends Comment where
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.3 `TextualRepresentation`. An `AnnotatingElement` giving
an alternate textual notation (in `language`, e.g. `"kerml"`/`"ocl"`/`"alf"`) for the
Element it represents (derived `representedElement` = its `owner`). -/
structure TextualRepresentation extends AnnotatingElement where
  body : String
  language : String
  deriving Repr

/-- KerML §8.3.2.4.4 `Namespace`. A named container of `Membership`s. Per the file
header, every one of `Namespace`'s own attributes in the spec (`member`, `ownedMember`,
`ownedMembership`, `importedMembership`, `/import`...) is derived from the
containment/import graph, so this adds no fields beyond `Element`'s -- it exists here
purely to anchor the generalization hierarchy (`Type` below specializes it). -/
structure Namespace extends Element where
  deriving Repr

/-- KerML §8.3.2.4.4 `VisibilityKind`: `private` (not visible outside the owning
Namespace), `protected` (default; equivalent to `private` for ordinary access/import),
`public` (publicly visible). -/
inductive VisibilityKind
  | «private» | «protected» | «public»
  deriving DecidableEq, Repr

/-- KerML §8.3.2.4.6 `Membership`. A `Relationship` making an Element (`memberElement`,
redefines `target`) a member of a `Namespace` (`membershipOwningNamespace`, derived).
`memberName`/`memberShortName` are the names used for resolution within that owning
Namespace. -/
structure Membership extends Relationship where
  memberElement : Element
  memberName : Option String := none
  memberShortName : Option String := none
  /-- Default `private` per KerML §8.3.2.4.6. -/
  visibility : VisibilityKind := .private
  deriving Repr

/-- KerML §8.3.2.4.9 `OwningMembership`, a `Membership` where the member is *owned*
(its `ownedMemberElement`/`ownedMemberElementId`/... are all `memberElement`-derived,
so no extra fields here). -/
structure OwningMembership extends Membership where
  deriving Repr

/-- KerML §8.3.2.4.2 `Import`. Abstract in the spec (only `MembershipImport`/
`NamespaceImport` are concrete). `isImportAll`: ignore declared visibility if true.
`isRecursive`: recursively import from owned sub-Namespaces. Spec constraint: a
root-namespace-owned `Import` must have `visibility = private` (not encoded here). -/
structure Import extends Relationship where
  isImportAll : Bool := false
  isRecursive : Bool := false
  /-- Default `private` per KerML §8.3.2.4.2. -/
  visibility : VisibilityKind := .private
  deriving Repr

/-- KerML §8.3.2.4.7 `MembershipImport`: imports a single `Membership`
(`importedMembership`, redefines `target`), recursively if `isRecursive` and its
target is itself a `Namespace`. -/
structure MembershipImport extends Import where
  importedMembership : Membership
  deriving Repr

/-- KerML §8.3.2.4.8 `NamespaceImport`: imports all visible memberships of a
`Namespace` (`importedNamespace`, redefines `target`), recursively if `isRecursive`. -/
structure NamespaceImport extends Import where
  importedNamespace : Namespace
  deriving Repr

end KerML.Root
