/-
Lean 4 formalization of the KerML (Kernel Modeling Language, OMG SysML v2 Release,
"Kernel Modeling Language v1.0 Beta 3") **Root** package's metamodel: KerML §8.2.3
"Root Concrete Syntax" and §8.3.2 "Root Abstract Syntax".

This is a *different* formalization concern from `SFS.lean`: `SFS.lean` translates
`~/git3/set.mm/SFS.mm`'s Metamath-level Supplemental Formal Semantics content (BLESS
Logic, Mereology, `df-model`, `df-rep`/`ElementRep`, `df-kind`/`ElementKind`, ...).
*This* file instead formalizes the real KerML metamodel itself -- the actual
`Element`/`Relationship`/`Namespace`/... metaclasses the OMG spec defines -- as its own
independent structure. Originally `SFS.lean` had its own separate, deliberately opaque
`KElement` stand-in ("SFS.mm has no Element/design primitive to reuse"), not identified
with this file's `Element`; as of 2026-08-20 (a full-replacement redesign, once this
file existed to replace it with), `KElement` is gone and `SFS.lean` now uses `Element`
here directly (`open KerML.Root (Element)`) wherever it used to use `KElement` --
`ElementRep`/`Model` in `SFS.lean`, and `ElementKind`/`Design`/`VT` in `Core.lean`
(moved there 2026-08-21), all reference this file's real `Element` now, not an opaque
placeholder.

## Scope (structural only, matching this project's established `Design`-for-`df-type`
precedent in `SFS.lean` for "whole containment graph" complexity)

Each metaclass below is a Lean `structure`, using `extends` to mirror KerML's
generalization hierarchy directly (Lean 4 structure extension gives real
subtyping-like projections, unlike a flat translation). Only **non-derived** (stored)
attributes are given fields; attributes marked `/` in the spec (derived, computed by
an OCL formula from other model state -- `owner`, `qualifiedName`, `ownedElement`,
`member`, effectively all of `Namespace`'s own attributes, etc.) are *not* included as
fields. Most of what's dropped this way is exactly the containment-graph structure
(`Element.ownedRelationship`, `Relationship.ownedRelatedElement`/`owningRelatedElement`
/`relatedElement`, `Namespace.member`/`ownedMember`/...): faithfully modeling that
graph would need `Element` and `Relationship` to reference each other, and doing that
justice (well-formedness of the ownership tree, name resolution, `qualifiedName`
computation, ...) is a substantially bigger project, deliberately out of scope here,
the same judgment call this project already made for `SFS.lean`'s `Design`. What *is*
kept: every metaclass's own non-derived, non-graph-structural
attributes (`elementId`, `declaredName`, `client`/`supplier`, `memberName`,
`visibility`, ...) and the generalization hierarchy itself.

OCL **constraints** (derivation/semantic/validation) are noted in prose in each
metaclass's doc comment, not encoded as Lean propositions or proved -- consistent with
the same "structural, not deeply verified" scope already used for `ElementRep`/`Model`
in `SFS.lean` and `ElementKind` in `Core.lean`.

Imported by `Core.lean` (KerML §8.2.4/§8.3.3) and, as of the `KElement` replacement
above, by `SFS.lean` and (transitively, via `SFS.lean`) `Assert.lean` too.
-/

import Lean

namespace KerML.Root

/-- KerML §8.3.2.1.2 `Element`. "A constituent of a model that is uniquely identified
relative to all other Elements. It can have Relationships with other Elements. Some of
these Relationships might imply ownership of other Elements, which means that if an
Element is deleted from a model, then so are all the Elements that it owns."
Non-derived attributes only (see file header) -- `ownedRelationship`, `/owner`,
`/qualifiedName`, `/name`, `/ownedElement`, `/documentation`, etc. are all omitted. -/
structure Element where
  /-- The globally unique identifier for this Element (set by tooling, must not
  change during the Element's lifetime). -/
  elementId : String
  /-- Alternative identifiers for this Element, generally set by tools. -/
  aliasIds : List String := []
  /-- The declared name of this Element. -/
  declaredName : Option String := none
  /-- An optional shorter/more succinct alternative name. -/
  declaredShortName : Option String := none
  deriving Repr

/-- KerML §8.3.2.1.3 `Relationship`. "An Element that relates other Element[s]. Some
of its relatedElements may be owned, in which case those ownedRelatedElements will be
deleted from a model if their owningRelationship is. ... The relatedElements of a
Relationship are divided into source and target Elements." Per the file header,
`ownedRelatedElement`/`owningRelatedElement`/`source`/`target`/`/relatedElement`
(the containment-graph edges) are deliberately omitted -- only `isImplied` is kept. -/
structure Relationship extends Element where
  /-- Whether this Relationship was generated by tooling to meet semantic rules,
  rather than being directly created by a modeler. -/
  isImplied : Bool := false
  deriving Repr

/-- KerML §8.3.2.2.2 `Dependency`. "A Relationship that indicates that one or more
client Elements require one more supplier Elements for their complete specification.
... entirely a model-level Relationship, without instance-level semantics." `client`
redefines `source`, `supplier` redefines `target` (both spec multiplicity `[1..*]`,
not enforced here). -/
structure Dependency extends Relationship where
  client : List Element
  supplier : List Element
  deriving Repr

/-- KerML §8.3.2.3.2 `AnnotatingElement`. "An Element that provides additional
description of or metadata on some other Element. ... either attached to its
annotatedElements by Annotation Relationships, or it implicitly annotates its
owningNamespace." Abstract in the spec (only `Comment`/`Documentation`/
`TextualRepresentation`/`MetadataFeature` are concretely instantiated); Lean doesn't
enforce that. All its own attributes (`annotatedElement`, `annotation`, ...) are
derived, so no extra fields beyond `Element`'s. -/
structure AnnotatingElement extends Element where
  deriving Repr

/-- KerML §8.3.2.3 `Annotation` (the Relationship an `AnnotatingElement` uses to
attach to what it annotates). `annotatedElement` redefines `target`. Spec constraint:
exactly one of `ownedAnnotatingElement`/`owningAnnotatingElement` is non-null (both
derived, not encoded here). -/
structure Annotation extends Relationship where
  annotatedElement : Element
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.2 `Comment`. An `AnnotatingElement` whose `body` is
free-text (possibly marked-up, e.g. HTML) annotation content. -/
structure Comment extends AnnotatingElement where
  body : String
  /-- POSIX locale of `body`'s natural-language text, if specified. -/
  locale : Option String := none
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.2 `Documentation`, a `Comment` whose `documentedElement`
(derived = its `owner`) is what it documents -- no extra stored attributes. -/
structure Documentation extends Comment where
  deriving Repr

/-- KerML §8.3.2.3.3/8.2.3.3.3 `TextualRepresentation`. An `AnnotatingElement` giving
an alternate textual notation (in `language`, e.g. `"kerml"`/`"ocl"`/`"alf"`) for the
Element it represents (derived `representedElement` = its `owner`). -/
structure TextualRepresentation extends AnnotatingElement where
  body : String
  language : String
  deriving Repr

/-- KerML §8.3.2.4.4 `Namespace`. A named container of `Membership`s. Per the file
header, every one of `Namespace`'s own attributes in the spec (`member`, `ownedMember`,
`ownedMembership`, `importedMembership`, `/import`...) is derived from the
containment/import graph, so this adds no fields beyond `Element`'s -- it exists here
purely to anchor the generalization hierarchy (`Type` below specializes it). -/
structure Namespace extends Element where
  deriving Repr

/-- KerML §8.3.2.4.4 `VisibilityKind`: `private` (not visible outside the owning
Namespace), `protected` (default; equivalent to `private` for ordinary access/import),
`public` (publicly visible). -/
inductive VisibilityKind
  | «private» | «protected» | «public»
  deriving DecidableEq, Repr

/-- KerML §8.3.2.4.6 `Membership`. A `Relationship` making an Element (`memberElement`,
redefines `target`) a member of a `Namespace` (`membershipOwningNamespace`, derived).
`memberName`/`memberShortName` are the names used for resolution within that owning
Namespace. -/
structure Membership extends Relationship where
  memberElement : Element
  memberName : Option String := none
  memberShortName : Option String := none
  /-- Default `private` per KerML §8.3.2.4.6. -/
  visibility : VisibilityKind := .private
  deriving Repr

/-- KerML §8.3.2.4.9 `OwningMembership`, a `Membership` where the member is *owned*
(its `ownedMemberElement`/`ownedMemberElementId`/... are all `memberElement`-derived,
so no extra fields here). -/
structure OwningMembership extends Membership where
  deriving Repr

/-- KerML §8.3.2.4.2 `Import`. Abstract in the spec (only `MembershipImport`/
`NamespaceImport` are concrete). `isImportAll`: ignore declared visibility if true.
`isRecursive`: recursively import from owned sub-Namespaces. Spec constraint: a
root-namespace-owned `Import` must have `visibility = private` (not encoded here). -/
structure Import extends Relationship where
  isImportAll : Bool := false
  isRecursive : Bool := false
  /-- Default `private` per KerML §8.3.2.4.2. -/
  visibility : VisibilityKind := .private
  deriving Repr

/-- KerML §8.3.2.4.7 `MembershipImport`: imports a single `Membership`
(`importedMembership`, redefines `target`), recursively if `isRecursive` and its
target is itself a `Namespace`. -/
structure MembershipImport extends Import where
  importedMembership : Membership
  deriving Repr

/-- KerML §8.3.2.4.8 `NamespaceImport`: imports all visible memberships of a
`Namespace` (`importedNamespace`, redefines `target`), recursively if `isRecursive`. -/
structure NamespaceImport extends Import where
  importedNamespace : Namespace
  deriving Repr

/-! ## Concrete syntax (KerML §8.2.3 "Root Concrete Syntax")

Real `syntax`/`elab` productions for the Root package's own concrete syntax, in the
same house style `Assert.lean`/`Core.lean` establish (`declare_syntax_cat`/
`syntax ... : category` productions, pure `MacroM (TSyntax `term)` elaborator
helpers). `kermlDecl` -- the shared "one KerML declaration" category every layer
(Root here, Core, Kernel) adds alternatives to -- is declared here rather than in
`Core.lean`, since `Root.lean` is the *earliest* file in the dependency chain
(`Core.lean` imports `Root`, `Kernel.lean` imports both): a category must be
declared before any file can add `syntax ... : <category>` alternatives to it, so
anchoring it at the root of the import graph is what lets `Root.lean` itself host
Root-layer productions (`doc`, `import`) as `kermlDecl` alternatives, the way real
KerML has Root-layer declarations (`Import`, `Comment`/`Documentation`, ...) as
alternatives of the same top-level declaration grammar Core/Kernel also extend.
`Core.lean`'s own Core-layer productions (`type`, `classifier`, `feature`, ...)
continue to add further `kermlDecl` alternatives from that file, unchanged -- only
the category *declaration* and the Root-layer productions themselves moved here;
`elabKermlDecl` (`Core.lean`), the single elaborator dispatching over every
`kermlDecl` alternative regardless of which file declared it, is unaffected. -/

open Lean

declare_syntax_cat kermlDecl

/-- KerML `QualifiedName` (§8.2.3.4.1, BNF line ~285): `A` or `A::B::C`. Used at
every *reference* position throughout the Root/Core/Kernel grammars (a
`specializes`/`typed by`/`subsets`/... target, or either operand of a standalone
relationship declaration) -- never for a *primary* declared name, which stays plain
`ident` (KerML's own `Identification`, not `QualifiedName`). Elaborates to a `String`
(`qualNameStr`, "::"-joined) used the same way a bare reference `ident`'s
`.getId.toString` always was -- still no symbol table, so `Anything::self` becomes a
stub carrying the string `"Anything::self"`, not an actual lookup of `Anything`'s
real `self` member; this is a strictly more faithful *label* for the reference than
dropping the qualifier ever was, not a resolution mechanism. -/
declare_syntax_cat kermlQualName
/-- `atomic(...)` on the repeated `"::" ident` group: without it, once `"::"` is
consumed inside one repetition attempt, a following token that isn't a valid `ident`
(e.g. the `*` in `import Kernel::* ;`'s wildcard suffix, parsed by a different,
*outer* production) is a hard parse error ("expected identifier") rather than a
graceful "this repetition doesn't apply, stop extending here, let the outer grammar
have the `::`" backtrack -- `atomic` makes a failed attempt fully unconsume so `*`
(the repetition combinator) can correctly stop at zero further repetitions instead of
propagating the failure. -/
syntax ident (atomic("::" ident))* : kermlQualName

def qualNameStr : TSyntax `kermlQualName → String
  | `(kermlQualName| $x:ident $[:: $xs:ident]*) =>
    String.intercalate "::" ((#[x] ++ xs).toList.map (·.getId.toString))
  | _ => "?"

/-- A `Membership`/`Import` visibility prefix (BNF `VisibilityIndicator`):
`public`/`private`/`protected`. Parsed but discarded -- `Import`'s own visibility
already defaults to `.private` (see `import`'s own doc comment below), so neither
`private import ...` nor `public import ...` (both real forms -- e.g. `Domain.kerml`'s
`private import ScalarValues::Real;` and `KerML.kerml`'s own `public import ...`)
actually flips a field, only needs to *parse*. `protected` isn't a production here --
no real file in this repo uses it on an `import`. -/
declare_syntax_cat kermlVisibilityFlag
syntax "private " : kermlVisibilityFlag
syntax "public " : kermlVisibilityFlag

/-- `doc "..."` stub for KerML `Documentation` (§8.2.3.3.2). Real KerML writes
`doc /* ... */`, a C-style block comment whose contents *are* the documentation
text -- lexing that needs a custom low-level parser this project doesn't attempt
(every other production here is built from existing token categories --
`ident`/`num`/`str`/literal keyword atoms -- never a raw custom one). `doc "..."`
(a plain quoted string, Lean's own `str` token) stands in for it: same
simplified-surface/faithful-structure trade this grammar already makes throughout
(`;` for `{ ... }`, bare `ident` for `QualifiedName`) -- `Base.kerml`'s literal
`doc /* This package defines... */` becomes `doc "This package defines..."` in the
smoke tests, not its exact text. `elementId` is a fixed placeholder (uniqueness not
enforced anywhere else in this grammar either). -/
def mkDocumentationStub (body : String) : Documentation := { elementId := "doc", body := body }
def Documentation.elt (d : Documentation) : Element := d.toComment.toAnnotatingElement.toElement

/-- Valid as a nested `kermlDecl` (so it appears inside a `kermlBody` alongside
sibling declarations, matching `Base.kerml`'s own `classifier Anything { doc ...
feature self ... }` shape) or standalone. Produces a `Documentation` element -- per
this grammar's established "no containment graph" principle, its *ownership* (which
element it documents) isn't modeled, only its existence as a sibling `Element`, same
as every other nested declaration. -/
syntax "doc " str : kermlDecl

/-- `MembershipImport`/`NamespaceImport` (§8.3.2.4.7/§8.3.2.4.8) stubs for
`import A::B ;` / `import A::* ;` respectively. As with every other reference in
this grammar, no symbol table means `importedMembership`/`importedNamespace` are
freshly-built minimal stub values (`memberElement`/nothing extra) carrying just the
referenced name, not real lookups. -/
def mkMembershipImportStub (name : String) : MembershipImport :=
  { elementId := "import-" ++ name,
    importedMembership := { elementId := name, memberElement := { elementId := name } } }
def mkNamespaceImportStub (name : String) : NamespaceImport :=
  { elementId := "import-" ++ name, importedNamespace := { elementId := name } }
def MembershipImport.elt (m : MembershipImport) : Element :=
  m.toImport.toRelationship.toElement
def NamespaceImport.elt (n : NamespaceImport) : Element :=
  n.toImport.toRelationship.toElement

/-- KerML §8.2.3.4.2 `Import` family: `import A::B ;` (one specific member) or
`import A::* ;` (every visible member of `A`), both with an optional
`private`/`public` prefix (`kermlVisibilityFlag` above -- parsed, not stored, see
that category's own doc comment). Being a `kermlDecl` alternative is what lets
`import` nest inside a `kermlBody` the way a real KerML import statement scopes to
the namespace/body it appears in -- any classifier/feature/predicate body that can
hold a nested `doc`/`feature` can equally hold a nested `import`, genuinely visible
to (in the same flat scope/list as) every sibling declaration in that same body, not
restricted to a fixed position. (Real name *resolution* against an import --
expanding a later bare `Assert` into `Assertion::Assert` because of an `import
Assertion::Assert;` earlier in the same scope -- is not attempted; this project has
no symbol table anywhere, and a bare reference already always becomes its own fresh
stub regardless of what's been imported, same as before this addition.) -/
syntax (kermlVisibilityFlag)? "import " kermlQualName "::" "*" " ;" : kermlDecl
syntax (kermlVisibilityFlag)? "import " kermlQualName " ;" : kermlDecl

end KerML.Root
